// <auto-generated />
namespace NTShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changekey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changekey));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271635510_changekey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
